# Generated by Django 5.1.4 on 2024-12-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='avatar',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
